/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTPrePlainliteral extends Token
{
    public TTPrePlainliteral()
    {
        super.setText("_plainliteral");
    }

    public TTPrePlainliteral(int line, int pos)
    {
        super.setText("_plainliteral");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPrePlainliteral(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPrePlainliteral(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPrePlainliteral text.");
    }
}
